######################################################################
##
## Filename: SPI_BUS.udo
## Created on: Tue Sep 05 10:27:29 PM China Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
