######################################################################
##
## Filename: SPI_BUS_Test.udo
## Created on: Tue Sep 05 9:47:12 PM China Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
