######################################################################
##
## Filename: usb_controller.udo
## Created on: Sat Sep 16 8:50:31 AM China Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
