######################################################################
##
## Filename: usb_controller_test.udo
## Created on: Fri Sep 15 11:11:12 PM China Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
